export const missions = [
  {
    promotionId: '9849a091-6082-452e-b327-dbcfa4e0a530',
    prizeType: 'Loyalty_Points',
    brandId: 'ossino',
    description: 'First to Hit 6X with minimum 0.00050 BTC or 0.5 mBTC',
    imageUrl:
      'https://rgs-dev-games.negroup-tech.net/ne-games-assets/site_assets/thumbnails/200/slide_200x200.webp',
    progress: 100,
    prizeAmount: 120,
    operatorId: 'ossino',
    providerId: 'negames',
    aggregator: 'negames',
    gameCode: 'slide',
    prizeAwarded: false,
  },
  {
    promotionId: 'd5e042f0-6da1-4256-95e4-4db3ab11150b',
    prizeType: 'Loyalty_Points',
    brandId: 'ossino',
    description: 'First to Hit 20X with minimum 0.00040 BTC or 0.4 mBTC',
    imageUrl:
      'https://rgs-dev-games.negroup-tech.net/ne-games-assets/site_assets/thumbnails/200/dice_200x200.webp',
    progress: 100,
    prizeAmount: 220,
    operatorId: 'ossino',
    providerId: 'negames',
    aggregator: 'negames',
    gameCode: 'dice',
    prizeAwarded: false,
  },
  {
    promotionId: '9752668d-d306-454d-af19-660df3a6a7b1',
    prizeType: 'Loyalty_Points',
    brandId: 'ossino',
    description: 'First to hit 40X with minimum 0.00020 BTC or 0.2 mBTC',
    imageUrl:
      'https://rgs-dev-games.negroup-tech.net/ne-games-assets/site_assets/thumbnails/200/defender_200x200.webp',
    progress: 100,
    prizeAmount: 250,
    operatorId: 'ossino',
    providerId: 'negames',
    aggregator: 'negames',
    gameCode: 'defender',
    prizeAwarded: false,
  },
  {
    promotionId: '7d1c7b66-be85-4906-b31f-ecd476cf93f7',
    prizeType: 'Loyalty_Points',
    brandId: 'ossino',
    description: 'First to Hit 10X with minimum 0.00015 BTC or 0.15 mBTC',
    imageUrl:
      'https://rgs-dev-games.negroup-tech.net/ne-games-assets/site_assets/thumbnails/200/rocket_boom_200x200.webp',
    progress: 100,
    prizeAmount: 150,
    operatorId: 'ossino',
    providerId: 'negames',
    aggregator: 'negames',
    gameCode: 'defender',
    prizeAwarded: false,
  },
  {
    promotionId: '51e29021-86bc-4802-95b1-0864256ec483',
    prizeType: 'Loyalty_Points',
    brandId: 'ossino',
    description: 'First to hit 50X with minimum 0.00023 BTC or 0.23 mBTC',
    imageUrl:
      'https://rgs-dev-games.negroup-tech.net/ne-games-assets/site_assets/thumbnails/200/mines_200x200.webp',
    progress: 100,
    prizeAmount: 100,
    operatorId: 'ossino',
    providerId: 'negames',
    aggregator: 'negames',
    gameCode: 'mines',
    prizeAwarded: false,
  },
  {
    promotionId: 'a42c639c-d941-407b-ac50-6d00ad7d6a3b',
    prizeType: 'Loyalty_Points',
    brandId: 'ossino',
    description: 'First to Hit 100X with minimum 0.00030 BTC or 0.3 mBTC',
    imageUrl:
      'https://rgs-dev-games.negroup-tech.net/ne-games-assets/site_assets/thumbnails/200/plinko_200x200.webp',
    progress: 100,
    prizeAmount: 200,
    operatorId: 'ossino',
    providerId: 'negames',
    aggregator: 'negames',
    gameCode: 'plinko',
    prizeAwarded: false,
  },
  {
    promotionId: 'ad39c018-45db-47a9-bf84-9c6b93dd2118',
    prizeType: 'Loyalty_Points',
    brandId: 'ossino',
    description: 'First to Hit 6X with minimum 0.00050 BTC or 0.5 mBTC',
    imageUrl:
      'https://rgs-dev-games.negroup-tech.net/ne-games-assets/site_assets/thumbnails/200/spinny_200x200.webp',
    progress: 100,
    prizeAmount: 200,
    operatorId: 'ossino',
    providerId: 'negames',
    aggregator: 'negames',
    gameCode: 'spinny',
    prizeAwarded: false,
  },
];
