import type { LevelsState } from './slice';

export const data: LevelsState['data'] = {
  overview: [
    {
      id: 1,
      feature: 'Cash Redemption on Loss Back',
      sprite: true,
      griffin: true,
      phoenix: true,
      dragon: true,
      chimera: true,
      hydra: true,
      leviathan: true,
    },
    {
      id: 2,
      feature: 'Level-Up Bonus',
      sprite: true,
      griffin: true,
      phoenix: true,
      dragon: true,
      chimera: true,
      hydra: true,
      leviathan: true,
    },
    {
      id: 3,
      feature: 'Daily Rewards',
      sprite: false,
      griffin: true,
      phoenix: true,
      dragon: true,
      chimera: true,
      hydra: true,
      leviathan: true,
    },
    {
      id: 4,
      feature: 'Daily Missions',
      sprite: false,
      griffin: false,
      phoenix: true,
      dragon: true,
      chimera: true,
      hydra: true,
      leviathan: true,
    },
    {
      id: 5,
      feature: 'Free Spins and Free Bets Redemption',
      sprite: false,
      griffin: false,
      phoenix: false,
      dragon: true,
      chimera: true,
      hydra: true,
      leviathan: true,
    },
    {
      id: 6,
      feature: 'Bonus Increase',
      sprite: false,
      griffin: false,
      phoenix: false,
      dragon: false,
      chimera: true,
      hydra: true,
      leviathan: true,
    },
    {
      id: 7,
      feature: 'VIP Page',
      sprite: false,
      griffin: false,
      phoenix: false,
      dragon: false,
      chimera: false,
      hydra: true,
      leviathan: true,
    },
  ],
  images: [
    {
      level: 'Sprite',
      image: "/images/levels/sprite.png",
    },
    {
      level: 'Griffin',
      image: "/images/levels/griffin.png",
    },
    {
      level: 'Phoenix',
      image: "/images/levels/phoenix.png",
    },
    {
      level: 'Dragon',
      image: "/images/levels/dragon.png",
    },
    {
      level: 'Chimera',
      image: "/images/levels/chimera.png",
    },
    {
      level: 'Hydra',
      image: "/images/levels/hydra.png",
    },
    {
      level: 'Leviathan',
      image: "/images/levels/leviathan.png",
    },
  ],
};
