export const config = {
  wrapperServiceUrl: import.meta.env.VITE_WRAPPER_SERVICE_URL,
  cyrusServiceUrl: import.meta.env.VITE_CYRUS_SERVICE_URL,
  loyaltyServiceUrl: import.meta.env.VITE_LOYALTY_SERVICE_URL,
  contentServiceUrl: import.meta.env.VITE_CONTENT_SERVICE_URL,
  gamesServiceUrl: import.meta.env.VITE_GAMES_SERVICE_URL,
  websiteUrl: import.meta.env.VITE_WEBSITE_URL,
  brandId: import.meta.env.VITE_BRAND_ID,
  googleClientId: import.meta.env.VITE_GOOGLE_CLIENT_ID,
  platformId: import.meta.env.VITE_PLATFORM_ID,
  operatorId: import.meta.env.VITE_OPERATOR_ID,
  loyaltyUsername: import.meta.env.VITE_LOYALTY_USERNAME,
  loyaltyPassword: import.meta.env.VITE_LOYALTY_PASSWORD,
  javaWrapperServiceUrl: import.meta.env.VITE_JAVA_WRAPPER_SERVICE_URL,
  newsStandingsServiceUrl: import.meta.env.VITE_JAVA_WRAPPER_FOR_NEWS_STANDINGS_SERVICE_URL,
  signalrHubUrl: import.meta.env.VITE_SIGNALR_HUB_URL,
  seasons: import.meta.env.VITE_SEASON,
  standingsFullPageSize: import.meta.env.VITE_STANDINGS_FULL_PAGE_SIZE,
  xClientId: import.meta.env.VITE_X_Client_Id,
} as const;
