import { type Bonus } from './slice';

export const bonuses: Bonus[] = [
  {
    id: 228488,
    date: new Date().toString(),
    name: 'Free Bet',
    type: 'Award Freebet',
    value: 500,
    applicableTo: 'Sports',
    expiryDate: new Date().toString(),
    expired: true,
    bonusUsageTotal: 500,
    bonusUsageCurrent: 470,
  },
  {
    id: 228489,
    date: new Date().toString(),
    name: 'Free Bet',
    type: 'Award Freebet',
    value: 500,
    applicableTo: 'Sports',
    expiryDate: new Date().toString(),
    expired: true,
    bonusUsageTotal: 500,
    bonusUsageCurrent: 470,
  },
  {
    id: 228490,
    date: new Date().toString(),
    name: 'Free Bet',
    type: 'Award Freebet',
    value: 500,
    applicableTo: 'Sports',
    expiryDate: new Date().toString(),
    expired: true,
    bonusUsageTotal: 500,
    bonusUsageCurrent: 470,
  },
  {
    id: 228491,
    date: new Date().toString(),
    name: 'Free Bet',
    type: 'Award Freebet',
    value: 500,
    applicableTo: 'Sports',
    expiryDate: new Date().toString(),
    expired: true,
    bonusUsageTotal: 500,
    bonusUsageCurrent: 470,
  },
];
